import React from 'react'

const Auditorium_1 = () => {
    return (
        <>
            <div className='d-flex flex-fill justify-content-center align-items-center bg-dark'>
                <div className='col-2 p-2'>
                    <div className='d-flex align-items-center'>
                        <div className='seat selected m-2'></div>
                        <div className='text-white'>Selected</div>
                    </div>
                    <div className='d-flex align-items-center'>
                        <div className='seat occupied m-2'></div>
                        <div className='text-white'>Occupied</div>
                    </div>
                    <div className='d-flex align-items-center'>
                        <div className='seat reserved m-2'></div>
                        <div className='text-white'>Reserved</div>
                    </div>
                </div>

                <div className='d-flex flex-column align-items-center col-10'>
                    <div className='screen shadow-lg d-flex'></div>
                    <div className="auditorium d-flex flex-column align-items-center">
                        <div className='d-flex mb-4'>
                            <div className="sector me-3">
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat occupied'></div>
                                    <div className='seat occupied'></div>
                                    <div className='seat occupied'></div>
                                    <div className='seat occupied'></div>
                                    <div className='seat occupied'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex justify-content-end'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                            </div>
                            <div className="sector ms-3">
                                <div className='d-flex'>
                                    <div className='seat selected'></div>
                                    <div className='seat reserved'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                            </div>
                        </div>
                        <div className='d-flex'>
                            <div className="sector me-3">
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat '></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                            </div>
                            <div className="sector ms-3">
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                                <div className='d-flex'>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                    <div className='seat'></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Auditorium_1